default:

  i18n:                                 # internationalization
    cultures:             [ en ]        # Available cultures
  
  cache:                                # Cache management
    apc:                  true          # (RECOMMENDED) Use Apc if available on current server

  js:
    compress:             true          # (RECOMMENDED) Performance : Minifies javascripts and put them into a single compressed file
    cdn:
      enabled:            false         # Will use cdn to load javascript libraries
      lib.jquery:         'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'
    head_inclusion:       [ ]           # If you want some libraries to be included in the <head> section,
                                        # declare them here. This degrades performances but is required
                                        # by some symfony plugins that embed jQuery code.
                                        # example: [ lib.jquery ]
    
  css:
    compress:             true          # (RECOMMENDED) Performance : Minifies stylesheets and put them into a single compressed file
    
  seo:                                  # Search engine optimization configuration
    use_keywords:         true          # Keywords are useless for seo, but you can use them if you want
    truncate:                           # Max length for meta fields. Can not exceed 255 characters
      slug:               255
      name:               255
      title:              80
      h1:                 255
      description:        160
      keywords:           255

  orm:                                  # Doctrine ORM configuration
                                        # More configuration : please use ProjectConfiguration::configureDoctrine method
    identifier_fields:    [ name, title, slug, subject, id ] # Fields used to represent a record with a string
    cache_enabled:        true          # (RECOMMENDED) Use doctrine query cache. No side effect, automatic cache invalidation )
    
  backup:                               # keep a copy of files modified by Dm code editors
    enabled:              true          # (RECOMMENDED) enable backup
  
  web_debug:                            # web debug panel configuration
    only_html_response:   true          # will skip web debug panel display on non html response
    config_fast_dump:     true          # use print_r instead of sfYaml::dump to show config in web debug panel. ( ~40x faster )
    
  toolBar:
    flavour:              blue          # the toolbar flavour. Diem default values: grey, blue, green, brown, black
                                        # You can also set a custom flavour and style #dm_tool_bar.flavour_name in your themeAdmin css path
  media:
    default:              false         # default resource to use when using _media with an empty resource.
                                        # example: /uploads/default.jpg
#    mime_type_whitelist: [ image/png] 

  security:
    remember_cookie_name:               # defaults to "dm_remember_%project_name%"
    remember_key_expiration_age:        # defaults to 15 days

  web_services:
    version_check:        true          # verifies regularly if you are using the latest Diem version.
    report_anonymous_data: true         # reports anonymous data about plugins used.
                                        # http://diem-project.org/plugins will show the best plugins based on these reports.
                                        # the report request is sent only once, when a superadministrator logs in.

  locks:                                # whether to enable real time resource locks
    enabled:              <?php echo sfConfig::get('sf_debug') ? "false\n" : "true\n"; ?>
    timeout:              10            # time in seconds to consider a user is no more active on the page

  performance:
    enable_mailer:        true          # Set to false to disable Swift loading: significant performance boost.
                                        # If set to false, you can enable the mailer on demand with dm::enableMailer()
    page_cache:                         # Will cache entire pages and serve them very fast.
      enabled:            false         # Enable the page cache for all pages
      life_time:          86400         # Server-side lifetime of the cache in seconds (86400 seconds equals one day)
 
###### dm internal config ######
  
  core:
    asset:                dmCorePlugin
  admin:
    asset:                dmAdminPlugin
  front:
    asset:                dmFrontPlugin